### ISSUE TITLE
readline() can return null.

### ISSUE THREAD

**Issue by simonvik** [xil-se/xildebug_cli#3]
readline returns null when you press for example ^+d

From documentation:

> readline returns the text of the line read.  A blank line returns the empty string.  If EOF is > encountered while reading a line, and the line is empty, NULL is returned.  If an EOF is read with a non-empty line, it is treated as a newline.

Something like the bellow would perhaps fix the issue.

```
if(line == NULL){
    break;
}
```

**Comment by simonvik** [comment]
(It coredumps if you press ctrl+d :))

**Comment by arturo182** [comment]
Fix: Don't press Ctrl+D
Issue resolved.
